config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"phrases#progress"

  resources :users, only: [:index,:show,:edit,:update]
  
  resources :phrases, only: [:new, :create,:edit, :update] do
    collection do
      get 'search'
    end
  end
  
  resources :rooms, only: [:index,:new,:create] do
    resources :messages, only: [:index, :create]
  end

  resources :articles
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :content
    validates :category_id
    validates :language_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :language
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'Question' },
    { id: 2, name: 'Life' },
    { id: 3, name: 'Travel' },
    { id: 4, name: 'Business' },
    { id: 5, name: 'Other' }
  ]

  include ActiveHash::Associations
  has_many :articles

end

app/models/language.rb
class Language < ActiveHash::Base
  self.data = [
    { id: 1, name: '日本語' },
    { id: 2, name: 'English' },
    { id: 3, name: 'Français' },
    { id: 4, name: 'Español' }
  ]

  include ActiveHash::Associations
  has_many :articles

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  has_many :phrase_tag_relations
  has_many :tags, through: :phrase_tag_relations
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :status
end

app/models/phrase_tag_relation.rb
class PhraseTagRelation < ApplicationRecord
  belongs_to :phrase
  belongs_to :tag
end

app/models/phrases_tag.rb
class PhrasesTag

  include ActiveModel::Model
  attr_accessor :native, :foreignA, :foreignB, :foreignC, :explanation, :status_id, :tagname, :user_id

  with_options presence: true do
    validates :native
    validates :tagname
    validates :user_id
  end

  def save(tag_list)
    phrase = Phrase.create(native:native, foreignA:foreignA, foreignB:foreignB, foreignC:foreignC, explanation:explanation, status_id:status_id, user_id:user_id)
    
    tag_list.each do |tagname|
      tag = Tag.where(tagname: tagname).first_or_initialize
      tag.save
      PhraseTagRelation.create(phrase_id: phrase.id, tag_id: tag.id)
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '0%' },
    { id: 2, name: '50%' },
    { id: 3, name: '100%' }
  ]

  include ActiveHash::Associations
  has_many :phrases

end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :phrase_tag_relations
  has_many :phrases, through: :phrase_tag_relations

  validates :tagname, uniqueness: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :phrases
  has_many :articles
  has_one_attached :image
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  
  with_options presence: true do
    validates :username
    validates :nationality
    validates :birthday
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles=Article.includes(:user).order("created_at DESC")
  end

  def new
    @article=Article.new
  end

  def create
    Article.create(article_params)
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article)
          .permit(:title,:content,:category_id,:language_id,:image).merge(user_id:current_user.id)
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  
  def progress
    @phrases = current_user.phrases
      
    # 日別登録数
    @progressdata=@phrases.group_by_day(:created_at).size
    @progresslabels = @progressdata.map(&:first) # 日付
    @progressdatas = @progressdata.map(&:second) # 個数
    
    # 累積登録数
    @cumulativedata = []
    sum=0
    @progressdatas.each do |p|
      sum = sum+p
      @cumulativedata<<sum
    end

    # パイチャート
    @pielabels=["100% (completed)","50%","0%"]
    @kkk=[]
    @phrases.each do |pie|
      @kkk<<pie.status_id
    end
    @piedatas=[@kkk.count(3),@kkk.count(2),@kkk.count(1)]

  end

  def new
    @phrase = PhrasesTag.new
  end

  def create
    @phrase = PhrasesTag.new(phrase_params)
    tag_list = params[:phrases_tag][:tagname].split(',')
    if @phrase.valid?
      @phrase.save(tag_list)
      
      return redirect_to root_path
    else
      render "new"
    end
  end

  def search
    @keywords = params[:keyword]
    if @keywords != "" && @keywords != nil     
      @split_keywords = @keywords.split(",")
      @phrases = Phrase.all
      @split_keywords.each do |keyword|
        @phrases=@phrases.where(['native LIKE(?) OR foreignA LIKE(?) OR foreignB LIKE(?) OR foreignC LIKE(?)',"%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])          
      end
      @phrasescount=@phrases.count
      @phrases=@phrases.page(params[:page]).per(10)
    end
  end

  def exrecise
  end


  private

  def phrase_params
    params.require(:phrases_tag).permit(:native, :foreignA, :foreignB, :foreignC, :explanation, :status_id, :tagname).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


  def new
    @room=Room.new
    
    @id=params[:key_id]
    @name=params[:key_name]
  end

  def create 
    Room.create(roomname:"#{params[:roomname]}",user_ids:params[:user_ids])
    redirect_to root_path
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  


  def index
    @users=User.where.not(id: current_user.id)
  end

  def show
    @user=User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :nationality,:image)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<div class="index-box">
<h2 class="mainarea-title">Articles</h2>

  <% @articles.each do |article| %>
    <div class="card">
      <div class="card-header">
        <%= "##{article.category.name}, ##{article.language.name}" %>
      </div>
      <div class="card-body">
        <h4 class="card-title"><%= "#{article.title}" %></h4>
        <p class="card-text"><%= "#{article.created_at} by #{article.user.username}" %></p>
        <span class="btn btn-light"><%= link_to "Detail",article_path(article.id) %></span>
      </div>
    </div>
  <% end %>
  
</div>

app/views/articles/new.html.erb
<div class="register-box">


<div class="mainarea-title">Post article</div>
<div class="form-container">
<%= form_with model: @article, url: articles_path, class:'form-wrap', local: true do |f| %>
  <div class='message-form'>
    <div class="message-field">
      <%= f.label :title,  "Title" %>
      <%= f.text_area :title, class:"input-message" %>
    </div>
    <div class="message-field">
      <%= f.label :content,  "Content" %>
      <%= f.text_area :content, class:"input-message" %>
    </div>
    <div class="message-field">
      <%= f.label :language_id,  "Language" %>
      <%= f.collection_select(:language_id, Language.all, :id, :name, {} )%>
    </div>
    <div class="message-field", id='tag-field'>
      <%= f.label :category_id, "Category" %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {} )%>
    </div>
    <div>Image
<%= f.file_field :image %>
</div>
    <div id="search-result">
    </div>
  </div>
  <div class="submit-post">
    <%= f.submit "Send", class: "submit-btn" %>
  </div>
<% end %>
</div>

</div>

app/views/rooms/index.html.erb
<%= render "messages/side_bar" %>

app/views/rooms/new.html.erb
<p></p>
<%= link_to "Confirm",rooms_path(user_ids:[@id,current_user.id], roomname:"#{@name}&#{current_user.username}" ), method: :post %>

app/views/users/edit.html.erb
<div class="login-box">

<div class="useredit">
<h2 class="mainarea-title">Edit profile</h2>

<%= form_with model: current_user, local: true do |f|%>
  <%# <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>



  <div>User Name
  <%= f.text_area :username, class:"input-default", id:"username", maxlength:"40" %>
  </div>
  <div>Nationality
  <%= f.text_area :nationality, class:"input-default", id:"nationality" %>
  </div>
  
  <div>Profile
  <%= f.text_area :profile, class:"input-default", id:"nationality" %>
  </div>
  <div>Image
  <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


</div>
</div>

app/views/users/index.html.erb
<div class="usershow_box">

<div class="usershow">
<h2 class="mainarea-title">Partners</h2>


<% @users.each do |user| %>
<div>
<% if user.image.attached? %>
<%= image_tag user.image.variant(resize: '150x150') %>
<% else %>
<%= image_tag "partner.png", size: "150x150" %>
<% end %>
<%= user.username %>
<%= user.nationality %>
<%= user.profile %>
<%= link_to "Profile",user_path(user.id) %>
</div>
<% end %>

</div>
</div>

app/views/users/show.html.erb
<div class="usershow_box">

<div class="usershow">
<h2 class="mainarea-title">Profile</h2>

<% if @user.image.attached? %>
<%= image_tag @user.image.variant(resize: '150x150') %>
<% else %>
<%= image_tag "partner.png", size: "150x150" %>
<% end %>
<%= @user.username %>
<%= @user.nationality %>
<%= @user.profile %>
<% if @user.id==current_user.id %>
<%= link_to "Edit profile",edit_user_path(current_user) %>
<% else %>
<%= link_to "Make chat room", new_room_path(key_id:@user.id,key_name:@user.username) %>
<% end %>
</div>
</div>