config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"phrases#progress"

  resources :users, only: [:index,:show,:edit,:update]
  
  resources :phrases, only: [:new, :create,:edit, :update] do
    collection do
      get 'search'
    end
  end
  
  resources :rooms, only: [:index,:new,:create] do
    resources :messages, only: [:index, :create]
  end

  resources :articles
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :content
    validates :category_id
    validates :language_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :language
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'Question' },
    { id: 2, name: 'Life' },
    { id: 3, name: 'Travel' },
    { id: 4, name: 'Business' },
    { id: 5, name: 'Other' }
  ]

  include ActiveHash::Associations
  has_many :articles

end

app/models/language.rb
class Language < ActiveHash::Base
  self.data = [
    { id: 1, name: '日本語' },
    { id: 2, name: 'English' },
    { id: 3, name: 'Français' },
    { id: 4, name: 'Español' }
  ]

  include ActiveHash::Associations
  has_many :articles

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  has_many :phrase_tag_relations
  has_many :tags, through: :phrase_tag_relations
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :status
end

app/models/phrase_tag_relation.rb
class PhraseTagRelation < ApplicationRecord
  belongs_to :phrase
  belongs_to :tag
end

app/models/phrases_tag.rb
class PhrasesTag

  include ActiveModel::Model
  attr_accessor :native, :foreignA, :foreignB, :foreignC, :explanation, :status_id, :tagname, :user_id

  with_options presence: true do
    validates :native
    validates :tagname
    validates :user_id
  end

  def save(tag_list)
    phrase = Phrase.create(native:native, foreignA:foreignA, foreignB:foreignB, foreignC:foreignC, explanation:explanation, status_id:status_id, user_id:user_id)
    
    tag_list.each do |tagname|
      tag = Tag.where(tagname: tagname).first_or_initialize
      tag.save
      PhraseTagRelation.create(phrase_id: phrase.id, tag_id: tag.id)
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '0%' },
    { id: 2, name: '50%' },
    { id: 3, name: '100%' }
  ]

  include ActiveHash::Associations
  has_many :phrases

end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :phrase_tag_relations
  has_many :phrases, through: :phrase_tag_relations

  validates :tagname, uniqueness: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :phrases
  has_many :articles
  has_one_attached :image
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  
  with_options presence: true do
    validates :username
    validates :nationality
    validates :birthday
  end
  
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  
  def progress
    @phrases = current_user.phrases
      
    # 日別登録数
    @progressdata=@phrases.group_by_day(:created_at).size
    @progresslabels = @progressdata.map(&:first) # 日付
    @progressdatas = @progressdata.map(&:second) # 個数
    
    # 累積登録数
    @cumulativedata = []
    sum=0
    @progressdatas.each do |p|
      sum = sum+p
      @cumulativedata<<sum
    end

    # パイチャート
    @pielabels=["100% (completed)","50%","0%"]
    @kkk=[]
    @phrases.each do |pie|
      @kkk<<pie.status_id
    end
    @piedatas=[@kkk.count(3),@kkk.count(2),@kkk.count(1)]

  end

  def new
    @phrase = PhrasesTag.new
  end

  def create
    @phrase = PhrasesTag.new(phrase_params)
    tag_list = params[:phrases_tag][:tagname].split(',')
    if @phrase.valid?
      @phrase.save(tag_list)
      
      return redirect_to root_path
    else
      render "new"
    end
  end

  def search
    @keywords = params[:keyword]
    if @keywords != "" && @keywords != nil     
      @split_keywords = @keywords.split(",")
      @phrases = Phrase.all
      @split_keywords.each do |keyword|
        @phrases=@phrases.where(['native LIKE(?) OR foreignA LIKE(?) OR foreignB LIKE(?) OR foreignC LIKE(?)',"%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])          
      end
      @phrasescount=@phrases.count
      @phrases=@phrases.page(params[:page]).per(10)
    end
  end

  def exrecise
  end


  private

  def phrase_params
    params.require(:phrases_tag).permit(:native, :foreignA, :foreignB, :foreignC, :explanation, :status_id, :tagname).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


  def new
    @room=Room.new
    
    @id=params[:key_id]
    @name=params[:key_name]
  end

  def create 
    Room.create(roomname:"#{params[:roomname]}",user_ids:params[:user_ids])
    redirect_to root_path
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  


  def index
    @users=User.where.not(id: current_user.id)
  end

  def show
    @user=User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :nationality,:image)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/phrases/new.html.erb
<div class="register-box">


<div class="mainarea-title">Register</div>
<div class="form-container">
<%= form_with model: @phrase, url: phrases_path, class:'form-wrap', local: true do |f| %>
  <div class='message-form'>
    <div class="message-field">
      <%= f.label :native,  "your native language" %>
      <%= f.text_area :native, class:"input-message" %>
    </div>
    <div class="message-field">
      <%= f.label :foreignA,  "English" %>
      <%= f.text_area :foreignA, class:"input-message" %>
    </div>
    <div class="message-field">
      <%= f.label :foreignB,  "Français" %>
      <%= f.text_area :foreignB, class:"input-message" %>
    </div>
    <div class="message-field">
      <%= f.label :foreignC,  "Español" %>
      <%= f.text_area :foreignC, class:"input-message" %>
    </div>
    <div class="message-field">
      <%= f.label :explanation,  "Explanation" %>
      <%= f.text_area :explanation, class:"input-message" %>
    </div>
    <div class="message-field">
      <%= f.label :status_id,  "status" %>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {} )%>
    </div>
    <div class="message-field", id='tag-field'>
      <%= f.label :tagname, "tag" %>
      <%= f.text_field :tagname, class:"input-tag" %>
    </div>
    <div id="search-result">
    </div>
  </div>
  <div class="submit-post">
    <%= f.submit "Send", class: "submit-btn" %>
  </div>
<% end %>
</div>

</div>

app/views/phrases/progress.html.erb
<div class="progress-box">

  <div class="progress-title">Your progress</div>
  
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="8000">

      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        
      </ol>

      <div class="carousel-inner"> 

        <div class="carousel-item active">
            <span class="d-block w-100">
              <h4 class="chart-title"><span>Plofiency level</span></h4>
              <h6 class="total">Total:<span class="num"><%= "#{@phrases.count} " %></span>phrases</h6>
              <canvas id="myChartPie"></canvas> 
              <script>
              
              var ctx = document.getElementById("myChartPie").getContext('2d');
              ctx.canvas.height = 240;
              var myChart = new Chart(ctx, {
                  type: 'doughnut',
                  data: {
                      
                      labels: <%= @pielabels.to_json.html_safe %>,
                      datasets: [{
                          label: "",
                          data: <%= @piedatas %>,
                          backgroundColor: [
                            "rgba(235, 58, 44, 0.7)",
                            "rgba(238, 239, 54, 0.7)",
                            "rgba(121, 204, 59, 0.7)"
                          ],
                          borderColor: 'rgba(0, 0, 0, 1.0)',
                          
                          fill: false
                      }]
                  },
                  options: {
                      
                      cutoutPercentage: 35,
                      
                      title:  {
                        display: false,
                        text: "",
                      },
                      legend: {
                      labels: {
                          
                          fontColor: 'black'
                      }
                  }
                  }
              });
              </script> 
            </span>
        </div>

        <div class="carousel-item">
            <span class="d-block w-100">
              <h4 class="chart-title"><span>Daily progress</span></h4>
              <h6 class="total">Total:<span class="num"><%= "#{@phrases.count} " %></span>phrases</h6>
              <canvas id="myChartProgress"></canvas> 
              <script>
              
              var ctx = document.getElementById("myChartProgress").getContext('2d');
              ctx.canvas.height = 240;
              var myChart = new Chart(ctx, {
                  type: 'bar',
                  data: {
                      //文字列の入った配列やハッシュ等はこうしないと正しく表示されない
                      labels: <%= @progresslabels.to_json.html_safe %>,
                      datasets: [{
                          label: "Daily number of posts",
                          data: <%= @progressdatas %>,
                          backgroundColor: 'rgba(235, 58, 44, 0.9)',
                          borderColor: 'black',
                          fill: false
                      },{
                          label: "Cumulative number of posts",
                          data: <%= @cumulativedata %>,
                          backgroundColor: 'rgba(11, 79, 33, 0.7)',
                          borderColor: 'rgba(235, 58, 44, 1.0)',
                          type: 'line',
                          lineTension: 0
                      }]
                  },
                  options: {
                      
                      title:  {
                        display: false,
                        text: "",
                      },
                      legend: {
                      labels: {
                          
                          fontColor: 'black'
                      },
                      },
                      scales: {                          // 軸設定
                          xAxes: [                           // Ｘ軸設定
                              {
                                  scaleLabel: {                 // 軸ラベル
                                      display: true,                // 表示設定
                                      labelString: 'Date',    // ラベル
                                      fontColor: "black",             // 文字の色
                                      fontSize: 16                  // フォントサイズ
                                  },
                                  gridLines: {                   // 補助線
                                      color: "black", // 補助線の色
                                  },
                                  ticks: {                      // 目盛り
                                      fontColor: "black",             // 目盛りの色
                                      fontSize: 14                  // フォントサイズ
                                  }
                              }
                          ],
                          yAxes: [                           // Ｙ軸設定
                              {
                                  scaleLabel: {                  // 軸ラベル
                                      display: true,                 // 表示の有無
                                      labelString: 'Phrases',     // ラベル
                                      fontFamily: "sans-serif",
                                      fontColor: "black",             // 文字の色
                                      fontFamily: "sans-serif",
                                      fontSize: 16                   // フォントサイズ
                                  },
                                  gridLines: {                   // 補助線
                                      color: "black", // 補助線の色
                                      zeroLineColor: "black"         // y=0（Ｘ軸の色）
                                  },
                                  ticks: {                       // 目盛り
                                      min: 0,                        // 最小値
                                      
                                      
                                      fontColor: "black",             // 目盛りの色
                                      fontSize: 14                   // フォントサイズ
                                  }
                              }
                          ]
                      }
                  }
              });
              </script> 
            </span>
        </div>

      </div>

      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>
  

</div>

app/views/phrases/search.html.erb
<div class="search-box">

<div class="mainarea-title">Search phrases</div>

<div class="search-form">
<%= form_with(url: search_phrases_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "String search", class: "search-input" %>
  <%= form.submit "search", class: "search-btn" %>
<% end %>

<%= form_with(url: search_phrases_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :tag, placeholder: "Tag search", class: "search-input" %>
  <%= form.submit "search", class: "search-btn" %>
<% end %>
</div>


<% if @phrases !=nil && @phrases!="" %>
<h4 class="search-result"><%= "'#{@keywords}' included :#{@phrasescount} phrases" %></h4>

<h5 class="checkbox-area"></h5>
<%= paginate @phrases %>
              <table class="table" id="targetTable" border="1">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        
                        <th scope="col">Tag</th>
                        <th scope="col">Native</th>
                        <th scope="col" id="english_display">English</th>
                        <th scope="col" id="french_display">Français</th>
                        <th scope="col" id="spanish_display">Español</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @phrases.each_with_index do |phrase, i| %>
                        <tr>
                            <td><%= i+1 %></td>
                            
                            <td>
                            <% phrase.tags.each do |tag| %>
                              <div><%= "# #{tag.tagname}"%></div>
                            <% end %>
                            </td>
                            <td><%= "#{phrase.native}"%></td>
                            <td><%= "#{phrase.foreignA}"%></td>
                            <td><%= "#{phrase.foreignB}"%></td>
                            <td><%= "#{phrase.foreignC}"%></td>
                            <td><%= link_to 'SHOW', edit_phrase_path(phrase.id), method: :get %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
  
<% end %>

</div>