config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"phrases#progress"

  resources :users, only: [:index,:show,:edit,:update]
  
  resources :phrases, only: [:new, :create,:edit, :update] do
    collection do
      get 'search'
    end
  end
  
  resources :rooms, only: [:index,:new,:create] do
    resources :messages, only: [:index, :create]
  end

  resources :articles
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :content
    validates :category_id
    validates :language_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :language
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'Question' },
    { id: 2, name: 'Life' },
    { id: 3, name: 'Travel' },
    { id: 4, name: 'Business' },
    { id: 5, name: 'Other' }
  ]

  include ActiveHash::Associations
  has_many :articles

end

app/models/language.rb
class Language < ActiveHash::Base
  self.data = [
    { id: 1, name: '日本語' },
    { id: 2, name: 'English' },
    { id: 3, name: 'Français' },
    { id: 4, name: 'Español' }
  ]

  include ActiveHash::Associations
  has_many :articles

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  has_many :phrase_tag_relations
  has_many :tags, through: :phrase_tag_relations
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :status
end

app/models/phrase_tag_relation.rb
class PhraseTagRelation < ApplicationRecord
  belongs_to :phrase
  belongs_to :tag
end

app/models/phrases_tag.rb
class PhrasesTag

  include ActiveModel::Model
  attr_accessor :native, :foreignA, :foreignB, :foreignC, :explanation, :status_id, :tagname, :user_id

  with_options presence: true do
    validates :native
    validates :tagname
    validates :user_id
  end

  def save(tag_list)
    phrase = Phrase.create(native:native, foreignA:foreignA, foreignB:foreignB, foreignC:foreignC, explanation:explanation, status_id:status_id, user_id:user_id)
    
    tag_list.each do |tagname|
      tag = Tag.where(tagname: tagname).first_or_initialize
      tag.save
      PhraseTagRelation.create(phrase_id: phrase.id, tag_id: tag.id)
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '0%' },
    { id: 2, name: '50%' },
    { id: 3, name: '100%' }
  ]

  include ActiveHash::Associations
  has_many :phrases

end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :phrase_tag_relations
  has_many :phrases, through: :phrase_tag_relations

  validates :tagname, uniqueness: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :phrases
  has_many :articles
  has_one_attached :image
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  
  with_options presence: true do
    validates :username
    validates :nationality
    validates :birthday
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


  def new
    @room=Room.new
    
    @id=params[:key_id]
    @name=params[:key_name]
  end

  def create 
    Room.create(roomname:"#{params[:roomname]}",user_ids:params[:user_ids])
    redirect_to root_path
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lingua2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%# slick %>
    <%# <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/> %>
    <%# <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/> %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%# chartjs %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>

    <%# bootstrap %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    
    <%# slick %>
    <%# <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script> %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
    
    <div class="wrapper">
    <div class="header">

      <div class="app-name">
        <%= link_to "Lingua", root_path, class:"app-name-link" %>
      </div>
      
      <% if user_signed_in? %>
      <div class="user-name">
        <div>
          <% if current_user.image.attached? %>
          <%= image_tag current_user.image.variant(resize: '40x40') %>
          <% else %>
          <%= image_tag "partner.png", size: "40x40" %>
          <% end %>
        </div>
        <div class="name"><%= current_user.username %></div>
        <div class="dropdown">
          <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <span class="dropdown-item"><%= link_to "Profile",user_path(current_user) %></span>
            
            <a class="dropdown-item" href="#">Notifications</a>
            <a class="dropdown-item" href="#">Settings</a>
            <span class="dropdown-item"><%= link_to "Log out",destroy_user_session_path, method: :delete %></span>
          </div>
        </div>
      </div>
      <% end %>
    
    </div>

    <% if user_signed_in? %>
    <div class="menu-bar">
      <div class="learning">
        <div class="dropdown">
          <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <span class="dropdown-item"><%= link_to "Progress",root_path %></span>
            <span class="dropdown-item"><%= link_to "Register",new_phrase_path %></span>
            <span class="dropdown-item"><%= link_to "Search phrases",search_phrases_path %></span>
            <a class="dropdown-item" href="#">Exercise</a>
          </div>
        </div>
        <div class="menu-title"> Learning</div>
      </div>
      
      <div class="communication">
        <div class="dropdown">
          <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <span class="dropdown-item"><%= link_to "Partners",users_path %></span>
            <span class="dropdown-item"><%= link_to "Chat rooms",rooms_path %></span>
         
          </div>
        </div>
        <div class="menu-title"> Communication</div>
      </div>


      <div class="articles">
        <div class="dropdown">
          <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <span class="dropdown-item"><%= link_to "Post article",new_article_path %></span>
            <span class="dropdown-item"><%= link_to "Search articles",articles_path %></span>
          </div>
        </div>
        <div class="menu-title">Articles</div>
      </div>
    
    </div>
    <% end %>


    <div class="main-area">
     <%= yield %>
    </div>


    </div>
  </body>

</html>